# Generated by Django 3.2.7 on 2022-03-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finestra',
            name='id_arduino',
            field=models.CharField(default='000', max_length=100),
        ),
        migrations.AddField(
            model_name='finestra',
            name='pin',
            field=models.CharField(default='A0', max_length=10),
        ),
    ]
