# Generated by Django 3.2.7 on 2022-03-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20220314_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finestra',
            old_name='id_arduino',
            new_name='device_name',
        ),
        migrations.RemoveField(
            model_name='finestra',
            name='posizione',
        ),
    ]
