# Generated by Django 3.2.7 on 2022-03-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20220315_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='finestra',
            name='timeout',
            field=models.BooleanField(default=False),
        ),
    ]
