# Generated by Django 3.2.7 on 2022-04-02 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_finestra_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='finestra',
            name='ultima_modifica',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
