# Generated by Django 3.2.7 on 2022-05-23 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20220402_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattelegram',
            name='ultimo_messaggio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 21, 16, 18, 460079)),
            preserve_default=False,
        ),
    ]
